In [1]:
import numpy as np
from sklearn.model_selection import StratifiedKFold
X = np.array([[1, 2], [3, 4], [5, 6], [7, 8]])
y = np.array([0,0,0,1])
skf = StratifiedKFold(n_splits=2)
skf.get_n_splits(X, y)

print(skf)

for train_index, test_index in skf.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')

StratifiedKFold(n_splits=2, random_state=None, shuffle=False)
TRAIN: [2 3] TEST: [0 1]
X_train 
 [[5 6]
 [7 8]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1]
y_test 
 [0 0]
*********************
TRAIN: [0 1] TEST: [2 3]
X_train 
 [[1 2]
 [3 4]]
X_test 
 [[5 6]
 [7 8]]
y_train 
 [0 0]
y_test 
 [0 1]
*********************


/Users/khalednada/opt/anaconda3/lib/python3.8/site-packages/sklearn/model_selection/_split.py:666: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=2.
  warnings.warn(("The least populated class in y has only %d"
