In [1]:
import numpy as np
from sklearn.model_selection import StratifiedShuffleSplit
X = np.array([[1, 2], [3, 4], [1, 2], [3, 4], [1, 2], [3, 4]])
y = np.array([0, 0, 0, 1, 1, 1])
sss = StratifiedShuffleSplit(n_splits=5, test_size=0.2, random_state=0)
sss.get_n_splits(X, y)
print(sss)
for train_index, test_index in sss.split(X, y):
    print("TRAIN:", train_index, "TEST:", test_index)
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]
    print('X_train \n' , X_train)
    print('X_test \n' , X_test)
    print('y_train \n' ,y_train)
    print('y_test \n' , y_test)
    print('*********************')

StratifiedShuffleSplit(n_splits=5, random_state=0, test_size=0.2,
            train_size=None)
TRAIN: [2 5 1 3] TEST: [0 4]
X_train 
 [[1 2]
 [3 4]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [1 2]]
y_train 
 [0 1 0 1]
y_test 
 [0 1]
*********************
TRAIN: [0 4 3 1] TEST: [2 5]
X_train 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 1 0]
y_test 
 [0 1]
*********************
TRAIN: [0 4 3 1] TEST: [2 5]
X_train 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 1 0]
y_test 
 [0 1]
*********************
TRAIN: [5 4 1 2] TEST: [0 3]
X_train 
 [[3 4]
 [1 2]
 [3 4]
 [1 2]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [1 1 0 0]
y_test 
 [0 1]
*********************
TRAIN: [1 5 2 4] TEST: [0 3]
X_train 
 [[3 4]
 [3 4]
 [1 2]
 [1 2]]
X_test 
 [[1 2]
 [3 4]]
y_train 
 [0 1 0 1]
y_test 
 [0 1]
*********************
