In [1]:

import numpy as np

from sklearn.impute import SimpleImputer

data = [[1,2,np.nan],
        [3,np.nan,1],
        [5,np.nan,0],
        [np.nan,4,6 ],
        [5,0,np.nan],
        [4,5,5]]

In [3]:
imp = SimpleImputer(missing_values=np.nan, strategy='median')

imp = imp.fit(data)

modifieddata = imp.transform(data)
print(modifieddata)

[[1. 2. 3.]
 [3. 3. 1.]
 [5. 3. 0.]
 [4. 4. 6.]
 [5. 0. 3.]
 [4. 5. 5.]]
